# Branch trigger
trigger:
- main

# VM pool to use
pool:
  vmImage: ubuntu-latest

# CI steps
steps:
# Install the required CLI
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g uilicious-cli
  displayName: 'Install the Uilicious CLI'
# And run it
- script: |
    uilicious-cli run "github-actions-demo" "hello-github" \
      --browser chrome \
      --key $(UILICIOUS_ACCESSKEY)
  displayName: 'Run test script'
