# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g uilicious-cli
  displayName: 'Install the Uilicious CLI'
- script: |
    uilicious-cli run "github-actions-demo" "hello-github" \
      --browser chrome \
      --key ${{ variables.UILICIOUS_ACCESSKEY }}
  displayName: 'Run test script'
