name: Uilicious CLI example
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  # Running a single test file
  cli-with-testfiles:
    runs-on: ubuntu-latest
    steps:
      # Repository checkout, node.js install, and cli install
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install the CLI
        run: npm install -g uilicious-cli
      # Actual cli run
      - name: Run a single test
        run: |
          uilicious-cli run "github-actions-demo" "hello-github" \
            --browser chrome \
            --key ${{ secrets.UILICIOUS_ACCESSKEY }}
  # Running using files local in your repository
  cli-with-local-testfiles:
    runs-on: ubuntu-latest
    steps:
      # Repository checkout, node.js install, and cli install
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install the CLI
        run: npm install -g uilicious-cli
      # Actual cli run
      - name: Run a single test
        run: |
          uilicious-cli run "github-actions-demo" "hello-github" \
            --browser chrome \
            --testCodeDir ./ui-test \
            --key ${{ secrets.UILICIOUS_ACCESSKEY }}
  # Running multiple tests in parallel
  cli-with-env-and-multiple-tests:
    runs-on: ubuntu-latest
    steps:
      # Repository checkout, node.js install, and cli install
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install the CLI
        run: npm install -g uilicious-cli
      # Actual cli run
      - name: Run multiple test concurrently
        run: |
          uilicious-cli run "github-actions-demo" "hello-github" --browser chrome > chrome-result.txt &
          uilicious-cli run "github-actions-demo" "hello-github" --browser firefox > firefox-result.txt &
          uilicious-cli run "github-actions-demo" "hello-github" --browser edge > edge-result.txt &
          wait
          cat ./*-result.txt
        env:
          UILICIOUS_ACCESSKEY: ${{ secrets.UILICIOUS_ACCESSKEY }}