name: Github Actions Example
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  action-with-test:
    runs-on: ubuntu-latest
    steps:
      - uses: omairvaiyani/ghact-uilicious@v1
        with:
          access-key: ${{ secrets.UILICIOUS_ACCESSKEY }}
          project: github-actions-demo
          tests: hello-github
          browser: chrome
  test-wildcard:
    runs-on: ubuntu-latest
    steps:
      - uses: omairvaiyani/ghact-uilicious@v1
        with:
          access-key: ${{ secrets.UILICIOUS_ACCESSKEY }}
          project: github-actions-demo
          tests: hello-*
          browser: chrome
          pattern: true
